In [1]:
import polars as pl
from pathlib import Path

In [2]:
nacc_etpr_path = Path('/projectnb/vkolagrp/projects/adrd_foundation_model/benchmarks/nacc_test_updated/test_etpr/test_etpr.jsonl')
nacc_etpr = pl.read_ndjson(nacc_etpr_path)

In [11]:
nacc_etpr.shape

(29788, 11)

In [7]:
nacc_etpr.select(pl.col('ground_truth_text').value_counts()).unnest('ground_truth_text')

shape: (8, 2)
┌─────────────────────────────────┬───────┐
│ ground_truth_text               ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ Psychiatric conditions includi… ┆ 205   │
│ Vascular brain injury or vascu… ┆ 403   │
│ Not applicable (no cognitive i… ┆ 13819 │
│ Lewy body disease (LBD)         ┆ 595   │
│ Systemic and environmental fac… ┆ 240   │
│ Alzheimer's disease (AD)        ┆ 13099 │
│ Frontotemporal lobar degenerat… ┆ 1258  │
│ Other (Multiple system atrophy… ┆ 169   │
└─────────────────────────────────┴───────┘

In [8]:
nacc_multi_path = Path('/projectnb/vkolagrp/projects/adrd_foundation_model/benchmarks/nacc_multilabel/nacc_multilabel.jsonl')
nacc_multi = pl.read_ndjson(nacc_multi_path)

In [12]:
nacc_multi.shape

(31029, 12)

In [14]:
nacc_multi.select(
    pl.col("PSY").value_counts()
).unnest('PSY')

shape: (3, 2)
┌─────┬───────┐
│ PSY ┆ count │
│ --- ┆ ---   │
│ i64 ┆ u32   │
╞═════╪═══════╡
│ 1   ┆ 205   │
│ 2   ┆ 2073  │
│ 0   ┆ 28751 │
└─────┴───────┘

In [15]:
example_res_path = Path('/projectnb/vkolagrp/bellitti/adrd-foundation-model/adrd_simplified_evaluation/results/mixed_dementia/nacc_multilabel/2025-10-27T12:21:53-NACC-3B-OS-SCE/nacc_multilabel_output_extracted_answers_last.parquet')
example = pl.read_parquet(example_res_path)

In [19]:
example.select(
    pl.col('PSY').value_counts()
).unnest('PSY').with_columns(
    pl.col('count')/5
)

shape: (3, 2)
┌─────┬─────────┐
│ PSY ┆ count   │
│ --- ┆ ---     │
│ i64 ┆ f64     │
╞═════╪═════════╡
│ 1   ┆ 205.0   │
│ 0   ┆ 28751.0 │
│ 2   ┆ 2073.0  │
└─────┴─────────┘

In [28]:
p = 205/31029

In [21]:
205*(1-0.006606)

203.64577

In [30]:
len(example) * p

1025.0

In [31]:
from numpy import sqrt

In [32]:
sqrt(len(example)* p * (1-p))

np.float64(31.909686761047638)