In [1]:
from pathlib import Path
import polars as pl
import re

In [2]:
multilabel_ans = Path('/projectnb/vkolagrp/bellitti/adrd-foundation-model/adrd_simplified_evaluation/results/mixed_dementia/nacc_multilabel/2025-10-27T12:21:53-NACC-os-sce/nacc_multilabel_output_extracted_answers_last.parquet')
df = pl.read_parquet(multilabel_ans)

In [3]:
df

shape: (155_145, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ generated ┆ finish_re ┆ NACCID    ┆ visit_sum ┆ … ┆ options   ┆ question  ┆ extracted ┆ predicti │
│ _text     ┆ ason      ┆ ---       ┆ mary      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ on       │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│ str       ┆ str       ┆           ┆ str       ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ To        ┆ stop      ┆ NACC28288 ┆ The       ┆ … ┆ A. Not    ┆ Using the ┆ A         ┆ A        │
│ identify  ┆           ┆ 5         ┆ subject   ┆   ┆ applicabl ┆ informati ┆           ┆          │
│ the contr ┆           ┆           ┆ is an 83- ┆   ┆ e, no     ┆ on        ┆           ┆          │
│ ibuting   ┆           ┆           ┆ year-old  ┆   ┆ cognitiv… ┆ provided… ┆           ┆          │
│ c…        ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ To        ┆ stop      ┆ NACC28288 ┆ The       ┆ … ┆ A. Not    ┆ Using the ┆ CD        ┆ CD       │
│ determine ┆           ┆ 5         ┆ subject   ┆   ┆ applicabl ┆ informati ┆           ┆          │
│ the contr ┆           ┆           ┆ is an 83- ┆   ┆ e, no     ┆ on        ┆           ┆          │
│ ibuting … ┆           ┆           ┆ year-old  ┆   ┆ cognitiv… ┆ provided… ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ To        ┆ stop      ┆ NACC28288 ┆ The       ┆ … ┆ A. Not    ┆ Using the ┆ C         ┆ C        │
│ determine ┆           ┆ 5         ┆ subject   ┆   ┆ applicabl ┆ informati ┆           ┆          │
│ the contr ┆           ┆           ┆ is an 83- ┆   ┆ e, no     ┆ on        ┆           ┆          │
│ ibuting … ┆           ┆           ┆ year-old  ┆   ┆ cognitiv… ┆ provided… ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ To        ┆ stop      ┆ NACC28288 ┆ The       ┆ … ┆ A. Not    ┆ Using the ┆ C         ┆ C        │
│ determine ┆           ┆ 5         ┆ subject   ┆   ┆ applicabl ┆ informati ┆           ┆          │
│ the contr ┆           ┆           ┆ is an 83- ┆   ┆ e, no     ┆ on        ┆           ┆          │
│ ibuting … ┆           ┆           ┆ year-old  ┆   ┆ cognitiv… ┆ provided… ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ To        ┆ stop      ┆ NACC28288 ┆ The       ┆ … ┆ A. Not    ┆ Using the ┆ ABCD      ┆ ABCD     │
│ identify  ┆           ┆ 5         ┆ subject   ┆   ┆ applicabl ┆ informati ┆           ┆          │
│ all the   ┆           ┆           ┆ is an 83- ┆   ┆ e, no     ┆ on        ┆           ┆          │
│ contribut ┆           ┆           ┆ year-old  ┆   ┆ cognitiv… ┆ provided… ┆           ┆          │
│ i…        ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ To        ┆ stop      ┆ NACC44927 ┆ The       ┆ … ┆ A. Other  ┆ Based on  ┆ D         ┆ D        │
│ determine ┆           ┆ 4         ┆ subject   ┆   ┆ Dementia  ┆ the       ┆           ┆          │
│ the main  ┆           ┆           ┆ is an 80- ┆   ┆ Etiology, ┆ clinical  ┆           ┆          │
│ causes o… ┆           ┆           ┆ year-old  ┆   ┆ in…       ┆ details,… ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ To        ┆ stop      ┆ NACC44927 ┆ The       ┆ … ┆ A. Other  ┆ Based on  ┆ D         ┆ D        │
│ determine ┆           ┆ 4         ┆ subject   ┆   ┆ Dementia  ┆ the       ┆           ┆          │
│ the main  ┆           ┆           ┆ is an 80- ┆   ┆ Etiology, ┆ clinical  ┆           ┆          │
│ causes o… ┆           ┆           ┆ year-old  ┆   ┆ in…       ┆ details,… ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ To        ┆ stop      ┆ NACC44927 ┆ The       ┆ … ┆ A. Other  ┆ Based on  ┆ AD        ┆ AD       │
│ determine ┆           ┆ 4         ┆ subject   ┆   ┆ Dementia  ┆ the       ┆           ┆          │
│ the main  ┆           ┆           ┆ is an 80- ┆   ┆ Etiology, ┆ clinical  ┆           ┆          │
│ causes o… ┆           ┆           ┆ year-old  ┆   ┆ in…       ┆ details,… ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ To        ┆ stop      ┆ NACC44927 ┆ The       ┆ … ┆ A. Other  ┆ Based on  ┆ AD        ┆ AD       │
│ determine ┆           ┆ 4         ┆ subject   ┆   ┆ Dementia  ┆ the       ┆           ┆          │
│ the main  ┆           ┆           ┆ is an 80- ┆   ┆ Etiology, ┆ clinical  ┆           ┆          │
│ causes o… ┆           ┆           ┆ year-old  ┆   ┆ in…       ┆ details,… ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ To        ┆ stop      ┆ NACC44927 ┆ The       ┆ … ┆ A. Other  ┆ Based on  ┆ AD        ┆ AD       │
│ determine ┆           ┆ 4         ┆ subject   ┆   ┆ Dementia  ┆ the       ┆           ┆          │
│ the main  ┆           ┆           ┆ is an 80- ┆   ┆ Etiology, ┆ clinical  ┆           ┆          │
│ causes f… ┆           ┆           ┆ year-old  ┆   ┆ in…       ┆ details,… ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
df['AD'].unique()

shape: (3,)
Series: 'AD' [i64]
[
	0
	1
	2
]

In [14]:
def make_option_dict(s):
    matches = re.findall(r'([A-Z])\. (.+)', s)

    options_dict = {letter: option for letter, option in matches}
    
    return options_dict

In [15]:
make_option_dict(df['options'][0])

{'A': 'Not applicable, no cognitive impairment.',
 'B': 'Frontotemporal Dementia (FTLD. Including CBD, PSP, with/without ALS).',
 'C': 'Systemic and External Factors (infectious, metabolic, substance abuse, etc.).',
 'D': 'Psychiatric Conditions (depression, bipolar, schizophrenia, anxiety, PTSD).',
 'E': 'Vascular Dementia.',
 'F': "Alzheimer's Disease",
 'G': "Lewy Body Disease (including Dementia with Lewy Bodies and Parkinson's disease).",
 'H': "Other Dementia Etiology, including MSA, Down's syndrome, Huntington's, Epilepsy, Neoplasm, and any etiology not appearing in another option."}