# QC generated summaries

Created by: Sahana Kowshik

In [1]:
import pandas as pd
import re
import json

In [2]:
def print_visit_summary(df, index):
    print(df.iloc[index]['visit_summary'])
    
def print_patient_summary(df, index):
    print(json.dumps(json.loads(df.iloc[index]['patient_summary']), indent=4))

In [3]:
# Define the path to the CSV you want to load:
# path = "/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/nacc/training_data/training_data_grpo/train_summary.csv"
# path = "/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/nacc/training_data/testing_data_grpo/test_summary.csv"
# path = "/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/nacc/training_data/testing_data_grpo/with_summary/test_pet.csv"
# path = "/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/nacc/training_data/testing_data_grpo/with_summary/test_csf.csv"
# path = "/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/nacc/training_data/testing_data_grpo/with_summary/test_dat.csv"
path = "/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/brainlat/training_data/testing_data_grpo/test_summary.csv"

# Read the data
summaries = pd.read_csv(path)
len(summaries)

713

In [4]:
len(summaries)

713

In [5]:
summaries.head()

,Diagnosis,Metadata,EEG Report,MRI Report,patient_summary,ID,visit_summary_prompt,visit_summary
0,Healthy,"{""Sex"": ""Female"", ""Years of education"": 20.0, ...",NaN,NaN,"{""Metadata"": {""Sex"": ""Female"", ""Years of educa...",sub-AR00167,<|im_start|>user\nYou will receive patient dat...,The patient is a female with 20 years of educa...
1,Alzheimer's disease,"{""Sex"": ""Female"", ""Age"": 72.0, ""Years of educa...",NaN,"{""MRI features extraction procedure"": ""A Gener...","{""Metadata"": {""Sex"": ""Female"", ""Age"": 72.0, ""Y...",sub-MXB00036,<|im_start|>user\nYou will receive patient dat...,The patient is a 72-year-old right-handed fema...
2,Healthy,"{""Sex"": ""Male"", ""Age"": 80.0, ""Years of educati...",NaN,"{""MRI features extraction procedure"": ""A Gener...","{""Metadata"": {""Sex"": ""Male"", ""Age"": 80.0, ""Yea...",sub-COB096,<|im_start|>user\nYou will receive patient dat...,The patient is an 80-year-old male with 16 yea...
3,Behavioral variant frontotemporal dementia,"{""Sex"": ""Female"", ""Age"": 68.0, ""Years of educa...",NaN,"{""MRI features extraction procedure"": ""A Gener...","{""Metadata"": {""Sex"": ""Female"", ""Age"": 68.0, ""Y...",sub-COB187,<|im_start|>user\nYou will receive patient dat...,The patient is a 68-year-old right-handed fema...
4,Alzheimer's disease,"{""Sex"": ""Male"", ""Age"": 88.0, ""Years of educati...",NaN,NaN,"{""Metadata"": {""Sex"": ""Male"", ""Age"": 88.0, ""Yea...",sub-CLB00134,<|im_start|>user\nYou will receive patient dat...,The patient is an 88-year-old male with 18 yea...

In [6]:
print_visit_summary(summaries, 0)

The patient is a female with 20 years of education and right-handed laterality. The neuropsychological assessment included the INECO Frontal Screening battery, which yielded a total score of 26 out of 30. Within this battery, the Motor Programming subset scored 3 out of 3, and the Conflicting Instructions subset also scored 3 out of 3. The Go/No Go subset received a score of 3 out of 3, while the Backward Digit Span subset was scored 3 out of 6. The Verbal Working Memory subset obtained a score of 2 out of 2, and the Spatial Working Memory subset received a score of 3 out of 4. The Abstraction Capacity subset was scored 3 out of 3, and the Verbal Inhibitory Control subset received a score of 6 out of 6. These scores reflect the patient's performance across various cognitive domains assessed by the INECO Frontal Screening tool.

In [ ]:
summaries['Q_TYPE'].value_counts()

In [33]:
print("Checking if amyloid is present in amyloid cases")
x = summaries[(summaries['Q_TYPE'] == 'Amyloid PET')]
print(len(x))
cnt = 0
for i, row in x.iterrows():
    if ('Abnormally elevated amyloid on PET' in row['patient_summary']):
        print(i, "ERROR available in patient_summary")
    if 'amyloid ' in row['visit_summary'].lower():
        print(i, "ERROR available in visit_summary")
        cnt += 1
    
    # if cnt > 5:
    #     break
    
x = summaries[(summaries['Q_TYPE'] == 'Amyloid CSF')]
print(len(x))
cnt = 0
for i, row in x.iterrows():
    if ('Abnormally low amyloid in CSF' in row['patient_summary']):
        print(i, "ERROR available in patient_summary")
    if 'amyloid ' in row['visit_summary'].lower():
        print(i, "ERROR available in visit_summary")
        cnt += 1
    
    # if cnt > 5:
    #     break

Checking if amyloid is present in amyloid cases
0
288
70 ERROR available in visit_summary

In [34]:
print("Checking if amyloid is not present in other cases")
x = summaries[~(summaries['Q_TYPE'].isin(['Amyloid PET', 'Amyloid CSF']))]
print(len(x))
cnt = 0
for i, row in x.iterrows():
    if ('Abnormally elevated amyloid on PET' in row['patient_summary']) | ('Abnormally low amyloid in CSF' in row['patient_summary']):
        # print(i, "ERROR NOT available in patient_summary")
        if 'amyloid' not in row['visit_summary'].lower():
            print(i, "ERROR NOT available in visit_summary")
            cnt += 1
            # break
    
    # if cnt > 5:
    #     break
    
# x = summaries[(summaries['Q_TYPE'] != 'Amyloid CSF')]
# print(len(x))
# cnt = 0
# for i, row in x.iterrows():
#     if ('Abnormally low amyloid in CSF' in row['patient_summary']):
#         print(i, "ERROR available in patient_summary")
#     if 'amyloid ' in row['visit_summary'].lower():
#         print(i, "ERROR available in visit_summary")
#         cnt += 1
    
#     # if cnt > 5:
#     #     break

Checking if amyloid is not present in other cases
0

In [8]:
import pandas as pd
import re
from collections import Counter

def find_repeated_sentences_in_text(text):
    # Split into sentences using punctuation (adjust if needed)
    sentences = re.split(r'(?<=[.!?])\s+', str(text).strip())
    normalized = [s.strip().lower() for s in sentences if s.strip()]
    counter = Counter(normalized)
    repeated = {sent: count for sent, count in counter.items() if count > 1}
    return repeated

repeats_info = []

for idx, row in summaries.iterrows():
    text = row['visit_summary']
    repeats = find_repeated_sentences_in_text(text)
    if repeats:
        for sentence, count in repeats.items():
            if count > 2:
                repeats_info.append({
                    "row_index": idx,
                    "sentence": sentence,
                    "count": count
                })

# Convert results to a DataFrame for easy analysis
repeats_df = pd.DataFrame(repeats_info)

In [9]:
repeats_df

Empty DataFrame
Columns: []
Index: []

In [10]:
if 'row_index' in repeats_df:
    repeat_list = set(repeats_df['row_index'])
else:
    repeat_list = set()

In [11]:
repeat_list

set()

In [39]:
summaries_dropped_index = summaries.drop(repeat_list).reset_index(drop=True)

In [40]:
# dropped = summaries.loc[list(repeat_list)]

In [41]:
# summaries.to_csv("/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/nacc/training_data/training_data_grpo/train_summary.csv", index=False)

In [42]:
# summaries_dropped_index = summaries

In [43]:
ages = []
for i, row in summaries_dropped_index.iterrows():
    pat = json.loads(row['patient_summary'])
    ages.append(pat['Subject Demographics']["Subject's age at visit"])

In [44]:
index = -1
incorrect_age_count = []
incorrect_cop_age_count = []

# Define regex pattern to extract and replace "a/an n-year-old"
age_pattern = r"\b(\d{1,3})-year-old\s\b"

def remove_incorrect_age(text):
    global count
    global index
    global incorrect_cop_age
    index += 1
    # Process text line by line
    modified_text = []
    for sentence in text.split("."):
        match = re.search(age_pattern, sentence)
        if match:  # Check if the sentence matches the pattern
            # print(sentence)
            age = match.group(1)  # Extract age
            # if "co-participant" in sentence.lower() or "spouse" in sentence.lower() or "child" in sentence.lower() or "daughter" in sentence.lower() or "friend" in sentence.lower() or "son" in sentence.lower() or "sibling" in sentence.lower() or "paid caregiver" in sentence.lower() or "relative" in sentence.lower():
            #     incorrect_cop_age_count.append((index, age))
                
            # else:   
            #     if int(age) != int(ages[index]):
            #         incorrect_age_count.append((index, age))
                    
            if int(age) != int(ages[index]) and 'co-participant' not in sentence:
                # print(text)
                incorrect_age_count.append((index, age, match, ages[index]))
            
    
    # return final_text

summaries_dropped_index["visit_summary"].apply(remove_incorrect_age)
print("Total sentences with incorrect co participant age:", len(incorrect_cop_age_count))
print("Total sentences with incorrect age:", len(incorrect_age_count))

Total sentences with incorrect co participant age: 0
Total sentences with incorrect age: 0

In [45]:
incorrect_age_count

[]

In [46]:
smoke_quit_age = []
for i, row in summaries_dropped_index.iterrows():
    pat = json.loads(row['patient_summary'])
    try:
        smoke_quit_age.append(pat['Subject Health History']["If the subject quit smoking, age at which he/she last smoked (i.e., quit) (range: (7.0 - 110.0))"])
    except:
        smoke_quit_age.append(-1)
        # pass

In [47]:
smoke_quit_age[4]

-1

In [48]:
import re

# Define regex pattern to identify relevant sentences
pattern = r"\b\d{1,3}-year-old individual\b.*?\bsmoking\b|\bsmoking\b.*?\b\d{1,3}-year-old\b"

# Define regex pattern to extract and replace "a/an n-year-old"
age_pattern_1 = r"\b(\d{1,3})-year-old\s\b"
age_pattern_2 = r"\bat age (\d{1,3})\s\b"

# Regex pattern to match "The patient quit smoking at the age of X"
quit_smoking_pattern = r"The patient quit smoking at the age of (\d+)"

In [49]:
index = 0
incorrect_smoking_age_count = []
invalid_smoking_age_count = []
quit_30_days_count = []

def clean_smoking_part(text):
    global count
    global index
    global invalid_smoking_age
    global quit_30_days_count
    
    modified_text = []
    
    for sentence in text.split("."):
        # sentence = sentence.strip()  # Remove leading/trailing spaces
        
        if "They quit smoking 30 days prior to the initial visit" in sentence:
            # sentence = sentence.replace("They quit smoking 30 days prior to the initial visit", "They did not smoke cigarettes for 30 days prior to the visit")
            quit_30_days_count.append(index)
        
        # Check for "The patient quit smoking at the age of X"
        quit_match = re.search(quit_smoking_pattern, sentence)
        if quit_match:
            age = int(quit_match.group(1))
            if int(age) > int(ages[index]):  
                invalid_smoking_age_count.append(index)
                continue

        # Check for "n-year-old" + "smoking"
        match = re.search(age_pattern_1, sentence)
        # if match and re.search(pattern, sentence):  
        if match and "smok" in sentence.lower(): 
            age = match.group(1)  # Extract age
            print(age)
            raise
            if int(age) != int(smoke_quit_age[index]):
                # sentence = re.sub(remove_pattern, "", sentence).strip()   # Replace "n-year-old" with ""
                incorrect_smoking_age_count.append((index, match))
        
        match = re.search(age_pattern_2, sentence)
        # if match and re.search(pattern, sentence):  
        if match and "smok" in sentence.lower(): 
            age = match.group(1)  # Extract age
            # print(age)
            # raise
            if int(age) != int(smoke_quit_age[index]):
                # sentence = re.sub(remove_pattern, "", sentence).strip()   # Replace "n-year-old" with ""
                incorrect_smoking_age_count.append((index, match))
            
            # if int(age) <= int(ages[index]) and (int(age) == int(smoke_quit_age[index]) and smoke_quit_age[index] != -1):
            #     # new_sentence = f"\n\nThe patient quit smoking at the age of {age}. "  # Create new sentence
            #     # modified_text.append(new_sentence + sentence)  # Add new sentence before original
            #     incorrect_smoking_age_count.append((index, match))
            # else:
            #     modified_text.append("\n\n" + sentence)
                # print(index)
                # raise ValueError
        # else:
        #     modified_text.append(sentence)  # Keep other sentences unchanged

    # Join sentences back into a full text
    # final_text = ".".join(modified_text)  # Removes any accidental empty sentences
    index += 1
    # return final_text

# Apply function to DataFrame column
summaries_dropped_index["visit_summary"].apply(clean_smoking_part)

print("Incorrect smoking age:", len(incorrect_smoking_age_count))
print("Invalid smoking age:", len(invalid_smoking_age_count))
print("Invalid quit_smoking_days:", len(quit_30_days_count))

Incorrect smoking age: 0
Invalid smoking age: 0
Invalid quit_smoking_days: 0

In [50]:
incorrect_smoking_age_count

[]

In [57]:
df = pd.read_csv("/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/nacc/training_data/training_data_grpo_modified_cog_np/train_with_questions.csv")

/scratch/ipykernel_2536336/2970543621.py:1: DtypeWarning: Columns (13,40,56,62,70,86,88,109,138,143,146,149,190,246,247,248,250,251,252,253,254,255,256,257,258,259,261,262,263,264,265,266,267,268,269,298,334,336,339,340,342,351,454,501,503,511,519,521,535,537,538,590,599,655,660,682,738,743,746,804,812,813,817,818,831,869,873,875,877,879,899,900,907,908,959,960,961,962,966,967,987,1000,1001,1016,1020,1021,1023,1036,1041,1044,1050,1054,1055,1059,1066,1070,1071,1073,1090,1200,1218,1219,1232,1233,1234,1235,1236,1237,1241,1243,1247,1251,1255,1264,1266,1272,1273,1275,1276,1277,1278,1279,1280,1281,1282,1283,1284,1285,1294,1296,1381,1397,1423,1475,1486,1594,1595,1596,1600,1625,1654,1655,1656,1657,1660,1690,1754,1786,1788,1793,1813,1816,1820,1825,1827,1867,1871,1876,1890,1892,1893,1914,1939,1941,1943,1945,1947,2011,2025,2033,2045,2047,2069,2071,2083,2085,2087,2089,2091) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/projectnb/vkolagrp/skowshik/foundation_adrd/adrd-foundation-model/data/nacc/training_data/training_data_grpo_modified_cog_np/train_with_questions.csv")

In [59]:
sub_df = df[df['Q_TYPE'] == "Primary etiology"]
sub_df.head()

,ID,patient_summary,diag_summary,question,options,ground_truth,ground_truth_text,Q_TYPE,visit_summary_prompt,visit_summary,...,VNTPCNC,VNTTOTW,WAIS,WEIGHT,WHITEVOL,WMHVOL,WONDRFUL,WRTHLESS,sort_key,sort_year
4,NACC215680,"{""Subject Demographics"": {""Subject's age at vi...","{""Clinician Judgment of Symptoms"": {""Does the ...","Using the information provided, identify the p...",A. Systemic and environmental factors includin...,B,Alzheimer's disease (AD),Primary etiology,<|im_start|>user\nYou will receive patient dat...,The subject is a 72-year-old male of Puerto Ri...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
6,NACC734580,"{""Subject Demographics"": {""Subject's age at vi...","{""Clinician Judgment of Symptoms"": {""Does the ...","Using the information provided, identify the p...",A. Not applicable (no cognitive impairment)\nB...,E,Lewy body disease (LBD),Primary etiology,<|im_start|>user\nYou will receive patient dat...,"The subject is a 64-year-old right-handed, Whi...",...,NaN,NaN,NaN,138.0,NaN,NaN,0.0,0.0,0,NaN
9,NACC833241,"{""Subject Demographics"": {""Subject's age at vi...","{""Clinician Judgment of Symptoms"": {""Does the ...",Identify the primary etiologic diagnosis of th...,"A. Other (Multiple system atrophy, Essential t...",B,Alzheimer's disease (AD),Primary etiology,<|im_start|>user\nYou will receive patient dat...,"The patient is a 75-year-old right-handed, Spa...",...,NaN,NaN,12.0,98.0,NaN,NaN,0.0,0.0,0,NaN
17,NACC927869,"{""Subject Demographics"": {""Subject's age at vi...","{""Clinician Judgment of Symptoms"": {""Does the ...",Identify the primary etiologic diagnosis of th...,A. Alzheimer's disease (AD)\nB. Vascular brain...,G,Frontotemporal lobar degeneration and its vari...,Primary etiology,<|im_start|>user\nYou will receive patient dat...,The patient is a 61-year-old White female who ...,...,NaN,NaN,32.0,144.0,NaN,NaN,1.0,1.0,0,NaN
20,NACC245783,"{""Subject Demographics"": {""Subject's age at vi...","{""Clinician Judgment of Symptoms"": {""Does the ...","Using the information provided, identify the p...",A. Frontotemporal lobar degeneration and its v...,G,Alzheimer's disease (AD),Primary etiology,<|im_start|>user\nYou will receive patient dat...,The subject is an 84-year-old female of Hispan...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN

In [61]:
sub_df['ground_truth_text'].value_counts()

ground_truth_text
Alzheimer's disease (AD)                                                                                                                                                                                             5000
Not applicable (no cognitive impairment)                                                                                                                                                                             3000
Frontotemporal lobar degeneration and its variants, including primary progressive aphasia, corticobasal degeneration and progressive supranuclear palsy, and with or without amyotrophic lateral sclerosis (FTLD)    1295
Lewy body disease (LBD)                                                                                                                                                                                               853
Vascular brain injury or vascular dementia including stroke (VD)                                                                                                                                                      579
Systemic and environmental factors including infectious diseases (HIV included), metabolic, substance abuse / alcohol, medications, systemic disease and delirium (SEF)                                               327
Psychiatric conditions including schizophrenia, depression, bipolar disorder, anxiety and posttraumatic stress disorder (PSY)                                                                                         176
Other (Multiple system atrophy, Essential tremor, Down syndrome, Huntington's disease, Prion disease, Traumatic brain injury, Normal-pressure hydrocephalus, Epilepsy, CNS neoplasm, etc)                             112
Name: count, dtype: int64

In [62]:
sub_df[sub_df['ground_truth_text'] == "Other (Multiple system atrophy, Essential tremor, Down syndrome, Huntington's disease, Prion disease, Traumatic brain injury, Normal-pressure hydrocephalus, Epilepsy, CNS neoplasm, etc)"]['NACCETPR'].value_counts()

NACCETPR
13    43
14    33
12    23
15     5
16     4
3      2
11     1
10     1
Name: count, dtype: int64